### PR TITLE
Delete duplicate typedef

### PR DESCRIPTION
**Pull request by ghost**
Should these need a second typedef? I'll let you answer that, because I can't, because I don't know.

### CODE REVIEW

**Comment by saintmarina** [comment]
If you delete one of the typedefs the code won't even compile.

**Comment by ghost** [comment]
> If you delete one of the typedefs the code won't even compile.

Is there a reason why it won't even compile/it needs a second typedef? I'm new to c and was wondering if there is a specific reason for it. Thanks.

**Comment by ghost** [comment]
Just making sure, you are referring to needing the second declaration of the same types on Lines 30-31 and 37-38, right? I'm fairly certain that a second declaration of the same two types is probably not needed.

**Comment by saintmarina** [comment]
Even thought the date and duration types are represented by the same int64, they are semantically different. While not needed, adding types improves readability and maintainability.

**Comment by ghost** [comment]
Ah, okay. Makes sense. Thanks for the info!

**Pull request closed without merging**
